# Generated by Django 5.0.6 on 2024-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
