# Generated by Django 5.0.6 on 2024-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
